FROM gmauro/ansible:2.6_ubuntu16.04
MAINTAINER Gianmauro Cuccuru <gmauro@crs4.it>

ENV DEBIAN_FRONTEND noninteractive

RUN git clone --recursive https://github.com/gmauro/galaxy4training \
 && cd galaxy4training \
 && ansible-playbook g4t.yml -e brand='CI'
