- hosts: galaxy_hosts
  become: true
  handlers:
    - name: restart galaxy
      supervisorctl:
        name: galaxy
        state: restarted

  tasks:
  - name: copy frontpage files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0644
    with_items:
      - { src: "{{ frontpage_welcome }}", dest: "{{ galaxy_root }}/server/static" }
      - { src: "{{ frontpage_footer }}", dest: "{{ galaxy_root }}/server/static/images" }
      - { src: "{{ frontpage_logo }}", dest: "{{ galaxy_root }}/server/static/images" }

  roles:
    - role: common
    - role: geerlingguy.pip
    - role: usegalaxy-eu.supervisor
    - role: geerlingguy.nginx
    - role: galaxyproject.cvmfs
      when: g4t_use_cvmfs_role | bool

  post_tasks:
    - name: Set tool_data_table_config_path to CVMFS one
      replace:
        path: "{{ galaxy_config_dir }}/galaxy.yml"
        regexp: '^    tool_data_table_config_path.*'
        replace: '    tool_data_table_config_path: {{ galaxy_root }}/var/config/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml'
      when: g4t_use_cvmfs_role | bool
      notify: restart galaxy

