- hosts: db_hosts
  become: true
  pre_tasks:
    - name: Install Dependencies
      package:
        name: 'python-psycopg2'
  roles:
    - role: common
    - role: galaxyproject.postgresql
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres