- hosts: galaxy_hosts
  become: true
  pre_tasks:
    - name: Only update apt cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install common dependencies
      package:
        pkg:
          - sudo
          - git-core
          - make
          - virtualenv
          - nano
          - vim
          - curl
          - unzip
          - samtools
          - zlib1g-dev
        state: present

    - name: Install OS specific dependencies
      package:
        pkg:
          - python-psycopg2
          - python-pip
        state: present
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version <= "16"
        -
    - name: Install OS specific dependencies
      package:
        pkg:
          - python3-psycopg2
          - python3-pip
        state: present
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version >= "18"

  roles:
    - role: common

  post_tasks:
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

